/**
  * @copyright Copyright (c) 2022, HiSilicon (Shanghai) Technologies Co., Ltd. All rights reserved.
  * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
  * following conditions are met:
  * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following
  * disclaimer.
  * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
  * following disclaimer in the documentation and/or other materials provided with the distribution.
  * 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote
  * products derived from this software without specific prior written permission.
  * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
  * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
  * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
  * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
  * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  * @file    flash_ip.h
  * @author  MCU Driver Team
  * @brief   FLASH module driver.
  * @details This file provides firmware functions to manage the following
  *          functionalities of the FLASH.
  *          + Register definition structure
  *          + Basic parameter configuration macro
  */

/* Define to prevent recursive inclusion ----------------------------------------*/
#ifndef McuMagicTag_FLASH_IP_H
#define McuMagicTag_FLASH_IP_H

/* Includes ---------------------------------------------------------------------*/
#include "baseinc.h"

/* Macro definitions -----------------------------------------------------------*/
#ifdef FLASH_PARAM_CHECK
#define FLASH_ASSERT_PARAM  BASE_FUNC_ASSERT_PARAM
#define FLASH_PARAM_CHECK_NO_RET BASE_FUNC_PARAMCHECK_NO_RET
#define FLASH_PARAM_CHECK_WITH_RET BASE_FUNC_PARAMCHECK_WITH_RET
#else
#define FLASH_ASSERT_PARAM(para)  ((void)0U)
#define FLASH_PARAM_CHECK_NO_RET(para) ((void)0U)
#define FLASH_PARAM_CHECK_WITH_RET(para, ret) ((void)0U)
#endif

/**
  * @addtogroup FLASH
  * @{
  */

/**
  * @defgroup FLASH_IP FLASH_IP
  * @brief FLASH_IP: flash_v3
  * @{
  */

#define FLASH_BASE                        0x0U            /* Flash PE operation base address. */
#define FLASH_READ_BASE                   0x3000000U      /* Base address for the flash read operation. */
#define FLASH_ONE_PAGE_SIZE               0x400U          /* Size of a page, unit: bytes. 1K. */
#define FLASH_ONE_PAGE_WORD_SIZE          0x100U          /* Size of a page, unit: word. 1K. */
#define FLASH_MAX_SIZE                    0x80000U        /* Flash space size 512k bytes. */

#define FLASH_KEY_REGISTER_UNLOCK_VALUE   0xFEDCBA98
#define FLASH_KEY_REGISTER_LOCK_VALUE     0x0

#define FLASH_MAX_PGM_BYTE_SIZE           0x100
#define FLASH_MAX_PGM_WORD_SIZE           0x40
#define FLASH_MIN_PGM_BYTES_SIZE          0x10
#define FLASH_MIN_PGM_WORDS_SIZE          4
#define FLASH_PGM_WORDS_LEGAL_DIVISOR     4
#define FLASH_ONE_WORD_BYTES_SIZE         4
#define FLASH_MAX_PAGE_NUM                512

#define FLASH_PGM_WBUF_CNT_POS            8
#define FLASH_PGM_WBUF_CNT_MASK          (0xFF << FLASH_PGM_WBUF_CNT_POS)

#define FLASH_MAX_CMD_PROGRAM_SIZE        0x10  /* The value is cmd program size, unit: 32bits. */

#define FLASH_SRAM_START_ADDRESS          0x02000000
#define FLASH_SRAM_END_ADDRESS            0x02010000
#define FLASH_MAIN_RNG_START_ADDRESS      0x03000000
#define FLASH_MAIN_RNG_END_ADDRESS        0x0307FFFF

/**
  * @defgroup FLASH_Param_Def FLASH Parameters Definition
  * @brief Definition of FLASH configuration parameters.
  * @{
  */
/* Typedef definitions --------------------------------------------------------*/
/**
  * @brief PE Operation Mode Enumeration Definition.
  */
typedef enum {
    FLASH_PE_OP_BLOCK = 0x00000000U,
    FLASH_PE_OP_IT    = 0x00000001U
} FLASH_PE_OpMode;

/**
  * @brief Erase operation type enumeration definition.
  */
typedef enum {
    FLASH_ERASE_MODE_PAGE = 0x00000004U,
    FLASH_ERASE_MODE_CHIP = 0x00000006U
} FLASH_EraseMode;

/**
  * @brief Flash page address enumeration.
  */
typedef enum {
    FLASH_PAGE_0 = FLASH_BASE,
    FLASH_PAGE_1 = FLASH_BASE + FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_2 = FLASH_BASE + 2 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_3 = FLASH_BASE + 3 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_4 = FLASH_BASE + 4 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_5 = FLASH_BASE + 5 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_6 = FLASH_BASE + 6 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_7 = FLASH_BASE + 7 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_8 = FLASH_BASE + 8 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_9 = FLASH_BASE + 9 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_10 = FLASH_BASE + 10 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_11 = FLASH_BASE + 11 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_12 = FLASH_BASE + 12 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_13 = FLASH_BASE + 13 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_14 = FLASH_BASE + 14 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_15 = FLASH_BASE + 15 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_16 = FLASH_BASE + 16 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_17 = FLASH_BASE + 17 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_18 = FLASH_BASE + 18 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_19 = FLASH_BASE + 19 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_20 = FLASH_BASE + 20 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_21 = FLASH_BASE + 21 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_22 = FLASH_BASE + 22 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_23 = FLASH_BASE + 23 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_24 = FLASH_BASE + 24 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_25 = FLASH_BASE + 25 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_26 = FLASH_BASE + 26 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_27 = FLASH_BASE + 27 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_28 = FLASH_BASE + 28 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_29 = FLASH_BASE + 29 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_30 = FLASH_BASE + 30 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_31 = FLASH_BASE + 31 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_32 = FLASH_BASE + 32 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_33 = FLASH_BASE + 33 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_34 = FLASH_BASE + 34 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_35 = FLASH_BASE + 35 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_36 = FLASH_BASE + 36 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_37 = FLASH_BASE + 37 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_38 = FLASH_BASE + 38 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_39 = FLASH_BASE + 39 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_40 = FLASH_BASE + 40 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_41 = FLASH_BASE + 41 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_42 = FLASH_BASE + 42 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_43 = FLASH_BASE + 43 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_44 = FLASH_BASE + 44 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_45 = FLASH_BASE + 45 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_46 = FLASH_BASE + 46 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_47 = FLASH_BASE + 47 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_48 = FLASH_BASE + 48 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_49 = FLASH_BASE + 49 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_50 = FLASH_BASE + 50 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_51 = FLASH_BASE + 51 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_52 = FLASH_BASE + 52 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_53 = FLASH_BASE + 53 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_54 = FLASH_BASE + 54 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_55 = FLASH_BASE + 55 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_56 = FLASH_BASE + 56 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_57 = FLASH_BASE + 57 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_58 = FLASH_BASE + 58 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_59 = FLASH_BASE + 59 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_60 = FLASH_BASE + 60 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_61 = FLASH_BASE + 61 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_62 = FLASH_BASE + 62 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_63 = FLASH_BASE + 63 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_64 = FLASH_BASE + 64 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_65 = FLASH_BASE + 65 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_66 = FLASH_BASE + 66 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_67 = FLASH_BASE + 67 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_68 = FLASH_BASE + 68 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_69 = FLASH_BASE + 69 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_70 = FLASH_BASE + 70 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_71 = FLASH_BASE + 71 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_72 = FLASH_BASE + 72 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_73 = FLASH_BASE + 73 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_74 = FLASH_BASE + 74 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_75 = FLASH_BASE + 75 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_76 = FLASH_BASE + 76 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_77 = FLASH_BASE + 77 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_78 = FLASH_BASE + 78 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_79 = FLASH_BASE + 79 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_80 = FLASH_BASE + 80 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_81 = FLASH_BASE + 81 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_82 = FLASH_BASE + 82 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_83 = FLASH_BASE + 83 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_84 = FLASH_BASE + 84 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_85 = FLASH_BASE + 85 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_86 = FLASH_BASE + 86 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_87 = FLASH_BASE + 87 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_88 = FLASH_BASE + 88 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_89 = FLASH_BASE + 89 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_90 = FLASH_BASE + 90 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_91 = FLASH_BASE + 91 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_92 = FLASH_BASE + 92 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_93 = FLASH_BASE + 93 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_94 = FLASH_BASE + 94 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_95 = FLASH_BASE + 95 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_96 = FLASH_BASE + 96 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_97 = FLASH_BASE + 97 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_98 = FLASH_BASE + 98 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_99 = FLASH_BASE + 99 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_100 = FLASH_BASE + 100 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_101 = FLASH_BASE + 101 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_102 = FLASH_BASE + 102 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_103 = FLASH_BASE + 103 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_104 = FLASH_BASE + 104 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_105 = FLASH_BASE + 105 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_106 = FLASH_BASE + 106 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_107 = FLASH_BASE + 107 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_108 = FLASH_BASE + 108 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_109 = FLASH_BASE + 109 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_110 = FLASH_BASE + 110 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_111 = FLASH_BASE + 111 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_112 = FLASH_BASE + 112 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_113 = FLASH_BASE + 113 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_114 = FLASH_BASE + 114 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_115 = FLASH_BASE + 115 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_116 = FLASH_BASE + 116 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_117 = FLASH_BASE + 117 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_118 = FLASH_BASE + 118 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_119 = FLASH_BASE + 119 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_120 = FLASH_BASE + 120 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_121 = FLASH_BASE + 121 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_122 = FLASH_BASE + 122 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_123 = FLASH_BASE + 123 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_124 = FLASH_BASE + 124 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_125 = FLASH_BASE + 125 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_126 = FLASH_BASE + 126 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_127 = FLASH_BASE + 127 * FLASH_ONE_PAGE_SIZE,

    /* Only this chips are supported 256K. */
#if defined (CHIP_3066MNPIRH) || defined (CHIP_3065PNPIMH) || defined (CHIP_3065PNPIRH) || defined (CHIP_3065PNPIRE)
    FLASH_PAGE_128 = FLASH_BASE + 128 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_129 = FLASH_BASE + 129 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_130 = FLASH_BASE + 130 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_131 = FLASH_BASE + 131 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_132 = FLASH_BASE + 132 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_133 = FLASH_BASE + 133 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_134 = FLASH_BASE + 134 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_135 = FLASH_BASE + 135 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_136 = FLASH_BASE + 136 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_137 = FLASH_BASE + 137 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_138 = FLASH_BASE + 138 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_139 = FLASH_BASE + 139 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_140 = FLASH_BASE + 140 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_141 = FLASH_BASE + 141 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_142 = FLASH_BASE + 142 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_143 = FLASH_BASE + 143 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_144 = FLASH_BASE + 144 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_145 = FLASH_BASE + 145 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_146 = FLASH_BASE + 146 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_147 = FLASH_BASE + 147 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_148 = FLASH_BASE + 148 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_149 = FLASH_BASE + 149 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_150 = FLASH_BASE + 150 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_151 = FLASH_BASE + 151 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_152 = FLASH_BASE + 152 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_153 = FLASH_BASE + 153 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_154 = FLASH_BASE + 154 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_155 = FLASH_BASE + 155 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_156 = FLASH_BASE + 156 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_157 = FLASH_BASE + 157 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_158 = FLASH_BASE + 158 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_159 = FLASH_BASE + 159 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_160 = FLASH_BASE + 160 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_161 = FLASH_BASE + 161 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_162 = FLASH_BASE + 162 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_163 = FLASH_BASE + 163 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_164 = FLASH_BASE + 164 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_165 = FLASH_BASE + 165 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_166 = FLASH_BASE + 166 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_167 = FLASH_BASE + 167 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_168 = FLASH_BASE + 168 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_169 = FLASH_BASE + 169 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_170 = FLASH_BASE + 170 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_171 = FLASH_BASE + 171 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_172 = FLASH_BASE + 172 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_173 = FLASH_BASE + 173 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_174 = FLASH_BASE + 174 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_175 = FLASH_BASE + 175 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_176 = FLASH_BASE + 176 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_177 = FLASH_BASE + 177 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_178 = FLASH_BASE + 178 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_179 = FLASH_BASE + 179 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_180 = FLASH_BASE + 180 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_181 = FLASH_BASE + 181 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_182 = FLASH_BASE + 182 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_183 = FLASH_BASE + 183 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_184 = FLASH_BASE + 184 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_185 = FLASH_BASE + 185 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_186 = FLASH_BASE + 186 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_187 = FLASH_BASE + 187 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_188 = FLASH_BASE + 188 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_189 = FLASH_BASE + 189 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_190 = FLASH_BASE + 190 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_191 = FLASH_BASE + 191 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_192 = FLASH_BASE + 192 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_193 = FLASH_BASE + 193 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_194 = FLASH_BASE + 194 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_195 = FLASH_BASE + 195 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_196 = FLASH_BASE + 196 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_197 = FLASH_BASE + 197 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_198 = FLASH_BASE + 198 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_199 = FLASH_BASE + 199 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_200 = FLASH_BASE + 200 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_201 = FLASH_BASE + 201 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_202 = FLASH_BASE + 202 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_203 = FLASH_BASE + 203 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_204 = FLASH_BASE + 204 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_205 = FLASH_BASE + 205 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_206 = FLASH_BASE + 206 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_207 = FLASH_BASE + 207 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_208 = FLASH_BASE + 208 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_209 = FLASH_BASE + 209 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_210 = FLASH_BASE + 210 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_211 = FLASH_BASE + 211 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_212 = FLASH_BASE + 212 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_213 = FLASH_BASE + 213 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_214 = FLASH_BASE + 214 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_215 = FLASH_BASE + 215 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_216 = FLASH_BASE + 216 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_217 = FLASH_BASE + 217 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_218 = FLASH_BASE + 218 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_219 = FLASH_BASE + 219 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_220 = FLASH_BASE + 220 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_221 = FLASH_BASE + 221 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_222 = FLASH_BASE + 222 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_223 = FLASH_BASE + 223 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_224 = FLASH_BASE + 224 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_225 = FLASH_BASE + 225 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_226 = FLASH_BASE + 226 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_227 = FLASH_BASE + 227 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_228 = FLASH_BASE + 228 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_229 = FLASH_BASE + 229 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_230 = FLASH_BASE + 230 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_231 = FLASH_BASE + 231 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_232 = FLASH_BASE + 232 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_233 = FLASH_BASE + 233 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_234 = FLASH_BASE + 234 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_235 = FLASH_BASE + 235 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_236 = FLASH_BASE + 236 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_237 = FLASH_BASE + 237 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_238 = FLASH_BASE + 238 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_239 = FLASH_BASE + 239 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_240 = FLASH_BASE + 240 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_241 = FLASH_BASE + 241 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_242 = FLASH_BASE + 242 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_243 = FLASH_BASE + 243 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_244 = FLASH_BASE + 244 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_245 = FLASH_BASE + 245 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_246 = FLASH_BASE + 246 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_247 = FLASH_BASE + 247 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_248 = FLASH_BASE + 248 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_249 = FLASH_BASE + 249 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_250 = FLASH_BASE + 250 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_251 = FLASH_BASE + 251 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_252 = FLASH_BASE + 252 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_253 = FLASH_BASE + 253 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_254 = FLASH_BASE + 254 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_255 = FLASH_BASE + 255 * FLASH_ONE_PAGE_SIZE,

    /* The chip is supported 128K. */
#if defined (CHIP_3065PNPIRE)
    FLASH_PAGE_MAX = FLASH_PAGE_255
#endif

    /* Only this chips are supported 512K. */
#if defined (CHIP_3066MNPIRH) || defined (CHIP_3065PNPIMH) || defined (CHIP_3065PNPIRH)
    FLASH_PAGE_256 = FLASH_BASE + 256 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_257 = FLASH_BASE + 257 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_258 = FLASH_BASE + 258 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_259 = FLASH_BASE + 259 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_260 = FLASH_BASE + 260 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_261 = FLASH_BASE + 261 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_262 = FLASH_BASE + 262 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_263 = FLASH_BASE + 263 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_264 = FLASH_BASE + 264 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_265 = FLASH_BASE + 265 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_266 = FLASH_BASE + 266 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_267 = FLASH_BASE + 267 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_268 = FLASH_BASE + 268 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_269 = FLASH_BASE + 269 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_270 = FLASH_BASE + 270 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_271 = FLASH_BASE + 271 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_272 = FLASH_BASE + 272 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_273 = FLASH_BASE + 273 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_274 = FLASH_BASE + 274 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_275 = FLASH_BASE + 275 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_276 = FLASH_BASE + 276 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_277 = FLASH_BASE + 277 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_278 = FLASH_BASE + 278 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_279 = FLASH_BASE + 279 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_280 = FLASH_BASE + 280 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_281 = FLASH_BASE + 281 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_282 = FLASH_BASE + 282 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_283 = FLASH_BASE + 283 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_284 = FLASH_BASE + 284 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_285 = FLASH_BASE + 285 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_286 = FLASH_BASE + 286 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_287 = FLASH_BASE + 287 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_288 = FLASH_BASE + 288 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_289 = FLASH_BASE + 289 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_290 = FLASH_BASE + 290 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_291 = FLASH_BASE + 291 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_292 = FLASH_BASE + 292 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_293 = FLASH_BASE + 293 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_294 = FLASH_BASE + 294 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_295 = FLASH_BASE + 295 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_296 = FLASH_BASE + 296 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_297 = FLASH_BASE + 297 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_298 = FLASH_BASE + 298 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_299 = FLASH_BASE + 299 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_300 = FLASH_BASE + 300 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_301 = FLASH_BASE + 301 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_302 = FLASH_BASE + 302 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_303 = FLASH_BASE + 303 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_304 = FLASH_BASE + 304 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_305 = FLASH_BASE + 305 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_306 = FLASH_BASE + 306 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_307 = FLASH_BASE + 307 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_308 = FLASH_BASE + 308 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_309 = FLASH_BASE + 309 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_310 = FLASH_BASE + 310 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_311 = FLASH_BASE + 311 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_312 = FLASH_BASE + 312 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_313 = FLASH_BASE + 313 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_314 = FLASH_BASE + 314 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_315 = FLASH_BASE + 315 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_316 = FLASH_BASE + 316 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_317 = FLASH_BASE + 317 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_318 = FLASH_BASE + 318 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_319 = FLASH_BASE + 319 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_320 = FLASH_BASE + 320 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_321 = FLASH_BASE + 321 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_322 = FLASH_BASE + 322 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_323 = FLASH_BASE + 323 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_324 = FLASH_BASE + 324 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_325 = FLASH_BASE + 325 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_326 = FLASH_BASE + 326 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_327 = FLASH_BASE + 327 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_328 = FLASH_BASE + 328 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_329 = FLASH_BASE + 329 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_330 = FLASH_BASE + 330 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_331 = FLASH_BASE + 331 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_332 = FLASH_BASE + 332 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_333 = FLASH_BASE + 333 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_334 = FLASH_BASE + 334 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_335 = FLASH_BASE + 335 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_336 = FLASH_BASE + 336 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_337 = FLASH_BASE + 337 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_338 = FLASH_BASE + 338 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_339 = FLASH_BASE + 339 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_340 = FLASH_BASE + 340 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_341 = FLASH_BASE + 341 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_342 = FLASH_BASE + 342 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_343 = FLASH_BASE + 343 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_344 = FLASH_BASE + 344 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_345 = FLASH_BASE + 345 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_346 = FLASH_BASE + 346 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_347 = FLASH_BASE + 347 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_348 = FLASH_BASE + 348 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_349 = FLASH_BASE + 349 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_350 = FLASH_BASE + 350 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_351 = FLASH_BASE + 351 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_352 = FLASH_BASE + 352 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_353 = FLASH_BASE + 353 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_354 = FLASH_BASE + 354 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_355 = FLASH_BASE + 355 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_356 = FLASH_BASE + 356 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_357 = FLASH_BASE + 357 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_358 = FLASH_BASE + 358 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_359 = FLASH_BASE + 359 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_360 = FLASH_BASE + 360 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_361 = FLASH_BASE + 361 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_362 = FLASH_BASE + 362 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_363 = FLASH_BASE + 363 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_364 = FLASH_BASE + 364 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_365 = FLASH_BASE + 365 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_366 = FLASH_BASE + 366 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_367 = FLASH_BASE + 367 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_368 = FLASH_BASE + 368 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_369 = FLASH_BASE + 369 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_370 = FLASH_BASE + 370 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_371 = FLASH_BASE + 371 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_372 = FLASH_BASE + 372 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_373 = FLASH_BASE + 373 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_374 = FLASH_BASE + 374 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_375 = FLASH_BASE + 375 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_376 = FLASH_BASE + 376 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_377 = FLASH_BASE + 377 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_378 = FLASH_BASE + 378 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_379 = FLASH_BASE + 379 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_380 = FLASH_BASE + 380 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_381 = FLASH_BASE + 381 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_382 = FLASH_BASE + 382 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_383 = FLASH_BASE + 383 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_384 = FLASH_BASE + 384 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_385 = FLASH_BASE + 385 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_386 = FLASH_BASE + 386 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_387 = FLASH_BASE + 387 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_388 = FLASH_BASE + 388 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_389 = FLASH_BASE + 389 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_390 = FLASH_BASE + 390 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_391 = FLASH_BASE + 391 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_392 = FLASH_BASE + 392 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_393 = FLASH_BASE + 393 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_394 = FLASH_BASE + 394 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_395 = FLASH_BASE + 395 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_396 = FLASH_BASE + 396 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_397 = FLASH_BASE + 397 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_398 = FLASH_BASE + 398 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_399 = FLASH_BASE + 399 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_400 = FLASH_BASE + 400 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_401 = FLASH_BASE + 401 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_402 = FLASH_BASE + 402 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_403 = FLASH_BASE + 403 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_404 = FLASH_BASE + 404 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_405 = FLASH_BASE + 405 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_406 = FLASH_BASE + 406 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_407 = FLASH_BASE + 407 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_408 = FLASH_BASE + 408 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_409 = FLASH_BASE + 409 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_410 = FLASH_BASE + 410 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_411 = FLASH_BASE + 411 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_412 = FLASH_BASE + 412 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_413 = FLASH_BASE + 413 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_414 = FLASH_BASE + 414 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_415 = FLASH_BASE + 415 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_416 = FLASH_BASE + 416 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_417 = FLASH_BASE + 417 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_418 = FLASH_BASE + 418 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_419 = FLASH_BASE + 419 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_420 = FLASH_BASE + 420 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_421 = FLASH_BASE + 421 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_422 = FLASH_BASE + 422 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_423 = FLASH_BASE + 423 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_424 = FLASH_BASE + 424 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_425 = FLASH_BASE + 425 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_426 = FLASH_BASE + 426 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_427 = FLASH_BASE + 427 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_428 = FLASH_BASE + 428 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_429 = FLASH_BASE + 429 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_430 = FLASH_BASE + 430 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_431 = FLASH_BASE + 431 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_432 = FLASH_BASE + 432 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_433 = FLASH_BASE + 433 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_434 = FLASH_BASE + 434 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_435 = FLASH_BASE + 435 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_436 = FLASH_BASE + 436 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_437 = FLASH_BASE + 437 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_438 = FLASH_BASE + 438 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_439 = FLASH_BASE + 439 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_440 = FLASH_BASE + 440 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_441 = FLASH_BASE + 441 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_442 = FLASH_BASE + 442 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_443 = FLASH_BASE + 443 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_444 = FLASH_BASE + 444 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_445 = FLASH_BASE + 445 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_446 = FLASH_BASE + 446 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_447 = FLASH_BASE + 447 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_448 = FLASH_BASE + 448 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_449 = FLASH_BASE + 449 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_450 = FLASH_BASE + 450 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_451 = FLASH_BASE + 451 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_452 = FLASH_BASE + 452 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_453 = FLASH_BASE + 453 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_454 = FLASH_BASE + 454 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_455 = FLASH_BASE + 455 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_456 = FLASH_BASE + 456 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_457 = FLASH_BASE + 457 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_458 = FLASH_BASE + 458 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_459 = FLASH_BASE + 459 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_460 = FLASH_BASE + 460 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_461 = FLASH_BASE + 461 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_462 = FLASH_BASE + 462 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_463 = FLASH_BASE + 463 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_464 = FLASH_BASE + 464 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_465 = FLASH_BASE + 465 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_466 = FLASH_BASE + 466 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_467 = FLASH_BASE + 467 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_468 = FLASH_BASE + 468 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_469 = FLASH_BASE + 469 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_470 = FLASH_BASE + 470 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_471 = FLASH_BASE + 471 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_472 = FLASH_BASE + 472 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_473 = FLASH_BASE + 473 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_474 = FLASH_BASE + 474 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_475 = FLASH_BASE + 475 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_476 = FLASH_BASE + 476 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_477 = FLASH_BASE + 477 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_478 = FLASH_BASE + 478 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_479 = FLASH_BASE + 479 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_480 = FLASH_BASE + 480 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_481 = FLASH_BASE + 481 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_482 = FLASH_BASE + 482 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_483 = FLASH_BASE + 483 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_484 = FLASH_BASE + 484 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_485 = FLASH_BASE + 485 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_486 = FLASH_BASE + 486 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_487 = FLASH_BASE + 487 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_488 = FLASH_BASE + 488 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_489 = FLASH_BASE + 489 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_490 = FLASH_BASE + 490 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_491 = FLASH_BASE + 491 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_492 = FLASH_BASE + 492 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_493 = FLASH_BASE + 493 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_494 = FLASH_BASE + 494 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_495 = FLASH_BASE + 495 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_496 = FLASH_BASE + 496 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_497 = FLASH_BASE + 497 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_498 = FLASH_BASE + 498 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_499 = FLASH_BASE + 499 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_500 = FLASH_BASE + 500 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_501 = FLASH_BASE + 501 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_502 = FLASH_BASE + 502 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_503 = FLASH_BASE + 503 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_504 = FLASH_BASE + 504 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_505 = FLASH_BASE + 505 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_506 = FLASH_BASE + 506 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_507 = FLASH_BASE + 507 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_508 = FLASH_BASE + 508 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_509 = FLASH_BASE + 509 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_510 = FLASH_BASE + 510 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_511 = FLASH_BASE + 511 * FLASH_ONE_PAGE_SIZE,
    FLASH_PAGE_MAX = FLASH_PAGE_511
#endif

#else
    /* The chip is supported 128K. */
    FLASH_PAGE_MAX = FLASH_PAGE_127
#endif

} FLASH_SectorAddr;

/**
  * @brief Flash operation word enumeration definition.
  */
typedef enum {
    FLASH_OPERATION_READ         = 0x00000001U,
    FLASH_OPERATION_PROGRAM      = 0x00000002U,
    FLASH_OPERATION_ERASE        = 0x00000004U,
    FLASH_OPERATION_MASS_ERASE   = 0x00000006U
} FLASH_OperationType;

/**
  * @brief Flash operation cmd code enumeration definition.
  */
typedef enum {
    FLASH_CMD_READ           = 0x00000001U,
    FLASH_CMD_MAIN_PROGEAM   = 0x00000002U,
    FLASH_CMD_INFO_PROGEAM   = 0x00000003U,
    FLASH_CMD_MAIN_ERASE     = 0x00000004U,
    FLASH_CMD_INFO_ERASE     = 0x00000005U,
    FLASH_CMD_MASS_ERASE     = 0x00000006U
} FLASH_CmdCodeType;

/**
  * @brief Callback Triggering Event Enumeration Definition
  */
typedef enum {
    FLASH_WRITE_EVENT_SUCCESS,
    FLASH_WRITE_EVENT_DONE,
    FLASH_WRITE_EVENT_FAIL,
    FLASH_ERASE_EVENT_SUCCESS,
    FLASH_ERASE_EVENT_DONE,
    FLASH_ERASE_EVENT_FAIL,
} FLASH_CallBackEvent;

/**
  * @brief FLASH extend handle, configuring some special parameters.
  */
typedef struct {
    unsigned int onceOperateLen; /* Length of the flash memory to be operaten, write unit: byte, erase unit: page. */
} FLASH_ExtendHandle;

/**
  * @brief User-defined callback function.
  */
typedef struct {
    /** Event callback function of the flash module */
    void (*FlashCallBack)(void *handle, FLASH_CallBackEvent event, unsigned int opAddr);
} FLASH_UserCallBcak;
/**
  * @}
  */

/**
  * @defgroup FLASH_Reg_Def FLASH Register Definition
  * @brief register mapping structure
  * @{
  */

/**
  * @brief EFLASH command registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int cmd_start     : 1; /**< Write 0:no effect, 1:start cmd operation;
                                             Read 0:cmd operation is complete, 1:cmd operation isn't complete. */
        unsigned int reserved0     : 5;
        unsigned int exec_state    : 2; /**< Read 0: no operation or operation completed,
                                                  1: an operation is being performed,
                                                  2: the operation is complete. */
        unsigned int cmd_code      : 3; /**< Values represent 1: read,
                                             2: main_rgn Program,
                                             3: info_rgn Program,
                                             4: main_rgn Erase,
                                             5: info_rgn Erase,
                                             6: mass erase. */
        unsigned int reserved1     : 9;
        unsigned int cmd_pgm_size  : 6; /**< Program Size, unit:word(32bits).
                                             0x0:2, 0x1:4, 0x2:8,..., 0x0F:60, 0x10:64,
                                             other values are invalid. */
        unsigned int reserved2     : 2;
        unsigned int cmd_read_size : 2; /**< Read Size, unit:word(32bits). 0x0:1, 0x1:4, 0x2:8, 0x3:12. */
        unsigned int reserved3     : 2;
    } BIT;
} volatile EFLASH_CMD_REG;

/**
  * @brief EFLASH address registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int reserved0 : 2;
        unsigned int cmd_addr : 22;   /**< Program, erase, or read start address register. Unit:byte(8bits).
                                           start address of Main_rgn: 0x00_0000,
                                           start address of info_rgn: 0x80_0000,
                                           note: the lower 2 bits cannot be written. */
        unsigned int reserved1 : 8;
    } BIT;
} volatile EFLASH_ADDR_REG;

/**
  * @brief Command configuration registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int reserved0 : 1;
        unsigned int int_mode : 1;   /**< Command operation mode 0:blocking mode, 1:interrupt mode. */
        unsigned int reserved1 : 30;
    } BIT;
} volatile CMD_CFG_COMMON_REG;

/**
  * @brief The raw interrupt status registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int reserved0            : 4;
        unsigned int int_raw_finish       : 1; /**< Operation completion status,
                                                    0:no operation performed or operation completed,
                                                    1:the operation completed. */
        unsigned int reserved1            : 11;
        unsigned int int_raw_err_illegal  : 1; /**< Invalid cmd operation errors, 0:no errors,
                                                    1:cmd operation error. */
        unsigned int int_raw_err_erase    : 1; /**< ERASE error, 0:pass, 1:failure. */
        unsigned int int_raw_err_ahb      : 1; /**< AHB request error, 0:no errors, 1:AHB read address request
                                                    exceeds the range of MAIN Information Region or
                                                    AHB write request occurs. */
        unsigned int int_raw_err_ecc_corr : 1; /**< MAIN Information Region Read Data ECC Correction Error,
                                                    0:no errors, 1:Uncorrectable ECC error occurred. */
        unsigned int int_raw_err_ecc_chk  : 1; /**< MAIN Information Region read data ECC error, 0:no errors,
                                                    1:an ECC check error occurred. */
        unsigned int reserved2            : 11;
    } BIT;
} volatile INT_RAW_STATUS_REG;

/**
  * @brief The interrupt status registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int reserved0        : 4;
        unsigned int int_finish       : 1;    /**< Operation completion status,
                                                   0:no operation performed or operation completed,
                                                   1:the operation completed. */
        unsigned int reserved1        : 11;
        unsigned int int_err_illegal  : 1;    /**< Invalid cmd operation errors, 0:no errors,
                                                   1:cmd operation error. */
        unsigned int int_err_erase    : 1;    /**< ERASE error, 0:pass, 1:failure. */
        unsigned int int_err_ahb      : 1;    /**< AHB request error, 0:no errors, 1:AHB read address request
                                                   exceeds the range of MAIN Information Region or
                                                   AHB write request occurs. */
        unsigned int int_err_ecc_corr : 1;    /**< MAIN Information Region Read Data ECC Correction Error, 0:no errors,
                                                   1:Uncorrectable ECC error occurred. */
        unsigned int int_err_ecc_chk  : 1;    /**< MAIN Information Region read data ECC error, 0:no errors,
                                                   1:an ECC check error occurred. */
        unsigned int reserved2        : 11;
    } BIT;
} volatile INT_STATUS_REG;

/**
  * @brief The interrupt enable configuration registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int reserved0           : 4;
        unsigned int int_en_finish       : 1;  /**< Operation completion interrupt enable, 0:disable, 1:enable. */
        unsigned int reserved1           : 11;
        unsigned int int_en_err_illegal  : 1;  /**< Invalid Cmd operation error interrupt enable,
                                                    0:disable, 1:enable. */
        unsigned int int_en_err_erase    : 1;  /**< ERASE error interrupt enable, 0:disable, 1:enable. */
        unsigned int int_en_err_ahb      : 1;  /**< AHB request error interrupt enable, 0:disable, 1:enable. */
        unsigned int int_en_err_ecc_corr : 1;  /**< Main Information region read data ECC correction error interrupt,
                                                    0:disable, 1:enable. */
        unsigned int int_en_err_ecc_chk  : 1;  /**< Main Information region read data ECC check error interrupt enable,
                                                    0:disable, 1:enable. */
        unsigned int reserved2           : 11;
    } BIT;
} volatile INT_ENABLE_REG;

/**
  * @brief Interrupt clear registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int reserved0            : 4;
        unsigned int int_clr_finish       : 1; /**< Operation completion interrupt clear, 0:not clear,
                                                    1:clear raw interrupts and interrupt status. */
        unsigned int reserved1            : 11;
        unsigned int int_clr_err_illegal  : 1; /**< Invalid CMD operation error interrupt clear, 0:not clear,
                                                    1:clear raw interrupts and interrupt status. */
        unsigned int int_clr_err_erase    : 1; /**< erase error interrupt clear, 0:not clear,
                                                    1:clear raw interrupts and interrupt status. */
        unsigned int int_clr_err_ahb      : 1; /**< AHB request error interrupt clear, 0:not clear,
                                                    1:clear raw interrupts and interrupt status. */
        unsigned int int_clr_err_ecc_corr : 1; /**< Main Information region read data ECC correction error
                                                    interrupt clear, 0:not clear,
                                                    1:clear raw interrupts and interrupt status. */
        unsigned int int_clr_err_ecc_chk  : 1; /**< Main Information region read data ECC error interrupt clear,
                                                    0:not clear, 1:clear raw interrupts and interrupt status. */
        unsigned int reserved2            : 11;
    } BIT;
} volatile INT_CLEAR_REG;

/**
  * @brief Prefetch control registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int prefetch_enable      : 1;  /**< Prefetch control enable, 0:disabled, 1:enable. */
        unsigned int reserved0            : 7;
        unsigned int prefetch_invalid_req : 1;  /**< Cache Data Invalid Request Control. */
        unsigned int reserved1            : 23;
    } BIT;
} volatile PREFETCH_CTRL_REG;

/**
  * @brief Cache control registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int cache_enable          : 1;   /**< Prefetch control enable, 0:disabled, 1:enable. */
        unsigned int reserved0             : 3;
        unsigned int cache_replacement_sel : 1;   /**< Cache replacement policy selection, 0:PLRU policy,
                                                       1:round robin policy. */
        unsigned int reserved1             : 3;
        unsigned int cache_invalid_req     : 1;   /**< Cache data invalid request, 0:invalidation,
                                                       1:request cache invalid. */
        unsigned int reserved2             : 3;
        unsigned int cache_policy_sel      : 1;   /**< Selecting a cache policy, 0:Normal Cache,
                                                       1:Branch Cache. */
        unsigned int reserved3             : 19;
    } BIT;
} volatile CACHE_CTRL_REG;

/**
  * @brief Flash ECC error detection and correction enable control registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int flash_main_ecc_check_enable   : 1;  /**< Flash Main region error detection enable,
                                                              0:no ECC check, 1:ECC check. */
        unsigned int flash_main_ecc_correct_enable : 1;  /**< Flash Main region error correction enable,
                                                              0:no ECC correction, 1:ECC correction. */
        unsigned int flash_info_ecc_check_enable   : 1;  /**< Flash Information region ECC error detection enable,
                                                              0:no ECC check, 1:ECC check. */
        unsigned int flash_info_ecc_correct_enable : 1;  /**< Flash Information region ECC error correction function,
                                                              0:no ECC correction, 1:ECC correction. */
        unsigned int flash_ecc_blank_filter_enable : 1;  /**< Flash unprogrammed area ECC mask and filter enable,
                                                              0:disable, 1:enable. */
        unsigned int reserved0                     : 27;
    } BIT;
} volatile FLASH_ECC_CTRL_REG;

/**
  * @brief Flash status registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int opcode_illegal    : 3;  /**< Invalid opcode value. */
        unsigned int reserved0         : 1;
        unsigned int mid_illegal       : 3;  /**< Invalid mid value. */
        unsigned int reserved1         : 1;
        unsigned int info_rgn0_illegal : 1;  /**< Illegally operation info_rgn0, 0:no error,
                                                  1:illegally access occurs. */
        unsigned int info_rgn1_illegal : 1;  /**< Illegally operation info_rgn1, 0:no error,
                                                  1:illegally access occurs. */
        unsigned int info_rgn2_illegal : 1;  /**< Illegally operation info_rgn2, 0:no error,
                                                  1:illegally access occurs. */
        unsigned int    info_rgn3_illegal     : 1   ; /* [11] */
        unsigned int    info_rgn4_illegal     : 1   ; /* [12] */
        unsigned int    reserved_2            : 2   ; /* [14..13] */
        unsigned int    main_rgn0_illegal     : 1   ; /* [15] */
        unsigned int    main_rgn1_illegal     : 1   ; /* [16] */
        unsigned int    main_rgn2_illegal     : 1   ; /* [17] */
        unsigned int    reserved_3            : 2   ; /* [19..18] */
        unsigned int    parameter_illegal     : 1   ; /* [20] */
        unsigned int    address_unmap         : 1   ; /* [21] */
        unsigned int    reserved_4            : 10  ; /* [31..22] */
    } BIT;
} volatile FLASH_STATUS_REG;

/**
  * @brief Main region 0 start address registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int reserved0            : 2;
        unsigned int main_rgn0_start_addr : 17;  /**< Region0 Access Start Address, Unit:Word(32bit). */
        unsigned int reserved1            : 13;
    } BIT;
} volatile FLASH_REGION_0_START_ADDR_REG;

/**
  * @brief Main region 0 end address registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int reserved0          : 2;
        unsigned int main_rgn0_end_addr : 17;  /**< Region0 Access End Address, Unit:Word(32bit). */
        unsigned int reserved1          : 13;
    } BIT;
} volatile FLASH_REGION_0_END_ADDR_REG;

/**
  * @brief Main region0 control registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int main_rgn0_mid_r  : 8;  /**< Indicates the mid that allows the read operation on region0. */
        unsigned int main_rgn0_mid_p  : 8;  /**< Indicates the MID that allows programming operations on region0. */
        unsigned int main_rgn0_mid_e  : 8;  /**< Indicates the MID that allows the erase operation on region0. */
        unsigned int reserved0        : 7;
        unsigned int main_rgn0_active : 1;  /**< Activate Zone Access Control, 0:not activated, 1:activated. */
    } BIT;
} volatile FLASH_REGION_0_CTRL_REG;

/**
  * @brief Main region 1 start address registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int reserved0            : 2;
        unsigned int main_rgn1_start_addr : 17;  /**< Region1 Access Start Address, Unit:Word(32bit). */
        unsigned int reserved1            : 13;
    } BIT;
} volatile FLASH_REGION_1_START_ADDR_REG;

/**
  * @brief Main region 1 end address registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int reserved0          : 2;
        unsigned int main_rgn1_end_addr : 17;  /**< Region1 Access end Address, Unit:Word(32bit). */
        unsigned int reserved1          : 13;
    } BIT;
} volatile FLASH_REGION_1_END_ADDR_REG;

/**
  * @brief Main region1 control registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int main_rgn1_mid_r  : 8;  /**< Indicates the mid that allows the read operation on region1. */
        unsigned int main_rgn1_mid_p  : 8;  /**< Indicates the MID that allows programming operations on region1. */
        unsigned int main_rgn1_mid_e  : 8;  /**< Indicates the MID that allows the erase operation on region1. */
        unsigned int reserved0        : 7;
        unsigned int main_rgn1_active : 1;  /**< Activate Zone Access Control, 0:not activated, 1:activated. */
    } BIT;
} volatile FLASH_REGION_1_CTRL_REG;

/* Define the union U_FLASH_REGION2_START_ADDR */
typedef union {
    unsigned int reg;
    struct {
        unsigned int    reserved_0            : 2   ; /* [1..0] */
        unsigned int    main_rgn2_start_addr  : 17  ; /* [18..2] */
        unsigned int    reserved_1            : 13  ; /* [31..19] */
    } BIT;
} volatile FLASH_REGION_2_START_ADDR_REG;

/* Define the union U_FLASH_REGION2_END_ADDR */
typedef union {
    unsigned int reg;
    struct {
        unsigned int    reserved_0            : 2   ; /* [1..0] */
        unsigned int    main_rgn2_end_addr    : 17  ; /* [18..2] */
        unsigned int    reserved_1            : 13  ; /* [31..19] */
    } BIT;
} volatile FLASH_REGION_2_END_ADDR_REG;

/* Define the union U_FLASH_REGION2_CTRL */
typedef union {
    unsigned int reg;
    struct {
        unsigned int    main_rgn2_mid_r       : 8   ; /* [7..0] */
        unsigned int    main_rgn2_mid_p       : 8   ; /* [15..8] */
        unsigned int    main_rgn2_mid_e       : 8   ; /* [23..16] */
        unsigned int    reserved_0            : 7   ; /* [30..24] */
        unsigned int    main_rgn2_active      : 1   ; /* [31] */
    } BIT;
} volatile FLASH_REGION_2_CTRL_REG;

/**
  * @brief Flash Module information 1 registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int page_size            : 16; /**< Info_rgn0/info_rgn1 capacity, unit:byte. */
        unsigned int information_capacity : 16; /**< Eflash page capacity, unit:byte. */
    } BIT;
} volatile EFLASH_CAPACITY_1_REG;

/**
  * @brief Flash Module information 2 registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int io_read_length              : 4; /**< Read I/O size. */
        unsigned int io_write_length_information : 4; /**< Write info region I/O size. */
        unsigned int io_write_length_main        : 4; /**< Write main region I/O size. */
        unsigned int min_pgm_size_information    : 4; /**< Minimal programming size of information region. */
        unsigned int min_pgm_size_main           : 4; /**< Minimal programming size of main region. */
        unsigned int max_pgm_size                : 4; /**< Max programming size. */
        unsigned int min_erase_size              : 4; /**< Minimal erase size. */
        unsigned int reserved0                   : 4;
    } BIT;
} volatile EFLASH_CAPACITY_2_REG;

/**
  * @brief Flash clears the programming data buffer registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int pgm_wdata_clr : 1;   /**< Clear Control, 0:no effect, 1:clear current buffer. */
        unsigned int reserved0     : 7;
        unsigned int pgm_wbuf_cnt  : 8;   /**< Obtains the size of the data in the buffer, unit:word. */
        unsigned int reserved1     : 16;
    } BIT;
} volatile BUF_CLEAR_REG;

/**
  * @brief Flash clock divider registers union structure definition.
  */
typedef union {
    unsigned int reg;
    struct {
        unsigned int    reserved0         : 4;
        unsigned int    nread_div         : 4;  /**< Ratio of the system bus master clock to EFlash clock (n + 1). */
        unsigned int    reserved1         : 12;
        unsigned int    busclk_sw_req     : 1;  /**< Check the cur_read_vref_cal or nread_div switchover is complete,
                                                     read 0:no finish, 1:finish. */
        unsigned int    busclk_sw_protect : 1;  /**< Frequency switching process protection, 0:enable, 1:disable. */
        unsigned int    cur_read_vref_cal : 1;  /**< Flash reference voltage calibration completion indicator. */
        unsigned int    reserved2         : 1;
        unsigned int    data_vld_sel      : 2;  /**< Data_vld: one beat in advance or one beat later,
                                                     0x0 and 0x01:no change, 0x02:take an early beat,
                                                     0x03:delay a beat */
        unsigned int    reserved3         : 6;
    } BIT;
} volatile EFLASH_CLK_CFG_REG;

/**
 * @brief FLASH Register definition structure
 */
typedef struct {
    EFLASH_CMD_REG                  EFLASH_CMD;               /**< Command register, Offset Address: 0x0000. */
    EFLASH_ADDR_REG                 EFLASH_ADDR;              /**< Address register, Offset Address: 0x0004. */
    unsigned char                   space0[120];
    CMD_CFG_COMMON_REG              CMD_CFG_COMMON;           /**< CMD configuration register,
                                                                   Offset Address: 0x0080. */
    unsigned char                   space1[124];
    INT_RAW_STATUS_REG              INT_RAW_STATUS;           /**< Raw interrupt status register,
                                                                   Offset Address: 0x0100. */
    INT_STATUS_REG                  INT_STATUS;               /**< Interrupt status register,
                                                                   Offset Address: 0x0104. */
    INT_ENABLE_REG                  INT_ENABLE;               /**< Interrupt enable configuration register,
                                                                   Offset Address: 0x0108. */
    INT_CLEAR_REG                   INT_CLEAR;                /**< Interrupt clear register,
                                                                   Offset Address: 0x010c. */
    unsigned char                   space2[16];
    PREFETCH_CTRL_REG               PREFETCH_CTRL;            /**< Prefetch control register,
                                                                   Offset Address: 0x0120. */
    CACHE_CTRL_REG                  CACHE_CTRL;               /**< Cache control register, Offset Address: 0x0124. */
    unsigned char                   space3[4];
    FLASH_ECC_CTRL_REG              FLASH_ECC_CTRL;           /**< Flash ECC error detection and correction enable
                                                                   control register, Offset Address: 0x012c. */
    FLASH_STATUS_REG                FLASH_STATUS;             /**< CMD operation flash status register,
                                                                   Offset Address: 0x0130. */
    unsigned char                   space4[4];
    unsigned int                    AHB_ERR_ADDR;             /**< AHB error request address record register,
                                                                   Offset Address: 0x0138. */
    unsigned char                   space5[8];
    FLASH_REGION_0_START_ADDR_REG   FLASH_REGION0_START_ADDR; /**< Main region 0 start address,
                                                                   Offset Address: 0x0144. */
    FLASH_REGION_0_END_ADDR_REG     FLASH_REGION0_END_ADDR;   /**< Main region 0 end address,
                                                                   Offset Address: 0x0148. */
    FLASH_REGION_0_CTRL_REG         FLASH_REGION0_CTRL;       /**< Main region0 control register,
                                                                   Offset Address: 0x014c. */
    FLASH_REGION_1_START_ADDR_REG   FLASH_REGION1_START_ADDR; /**< Main region 1 start address,
                                                                   Offset Address: 0x0150. */
    FLASH_REGION_1_END_ADDR_REG     FLASH_REGION1_END_ADDR;   /**< Main region 1 end address,
                                                                   Offset Address: 0x0154. */
    FLASH_REGION_1_CTRL_REG         FLASH_REGION1_CTRL;       /**< Main region 1 control register,
                                                                   Offset Address: 0x0158. */
    FLASH_REGION_2_START_ADDR_REG   FLASH_REGION2_START_ADDR;
    FLASH_REGION_2_END_ADDR_REG     FLASH_REGION2_END_ADDR;
    FLASH_REGION_2_CTRL_REG         FLASH_REGION2_CTRL;
    unsigned char                   space6[152];
    unsigned int                    MAGIC_LOCK;               /**< CMD magic word protection register,
                                                                   Offset Address: 0x0200. */
    unsigned char                   space7[492];
    unsigned int                    EFLASH_CAPACITY_0;        /**< Module information register 0,
                                                                   Offset Address: 0x03f0. */
    EFLASH_CAPACITY_1_REG           EFLASH_CAPACITY_1;        /**< Module information register 1,
                                                                   Offset Address: 0x03f4. */
    EFLASH_CAPACITY_2_REG           EFLASH_CAPACITY_2;        /**< Module information register 2,
                                                                   Offset Address: 0x03f8. */
    unsigned char                   space8[4];
    unsigned int                    PGM_WDATA;                /**< Program data register, Offset Address: 0x0400. */
    unsigned char                   space9[508];
    unsigned int                    FLASH_RDATA;              /**< Read data register, Offset Address: 0x0600. */
    BUF_CLEAR_REG                   BUF_CLEAR;                /**< Programming data buffer cleanup register,
                                                                   Offset Address: 0x0604. */
    unsigned int                    space10[206];
    EFLASH_CLK_CFG_REG              EFLASH_CLK_CFG;           /**< Clock divider register, Offset Address: 0x0940. */
} volatile EFC_RegStruct;

/**
  * @}
  */

/* Parameter check definition-------------------------------------------*/
/**
  * @brief Check Operation mode selection.
  * @param opMode Flash Operation mode.
  * @retval true
  * @retval false
  */
static inline bool IsFlashOperationMode(FLASH_PE_OpMode opMode)
{
    return (opMode == FLASH_PE_OP_BLOCK ||
            opMode == FLASH_PE_OP_IT);
}

/**
  * @brief Check flash cmd code.
  * @param cmdCode Flash cmd code.
  * @retval true
  * @retval false
  */
static inline bool IsFlashCmdCode(FLASH_CmdCodeType cmdCode)
{
    return (cmdCode == FLASH_CMD_READ || cmdCode == FLASH_CMD_MAIN_PROGEAM || \
            cmdCode == FLASH_CMD_INFO_PROGEAM || cmdCode == FLASH_CMD_MAIN_ERASE || \
            cmdCode == FLASH_CMD_INFO_ERASE || cmdCode == FLASH_CMD_MASS_ERASE);
}

/**
  * @brief Check flash cmd program size.
  * @param size cmd program size, unit:Word(32bit).
  * @retval true
  * @retval false
  */
static inline bool IsFlashCmdProgramSize(unsigned int size)
{
    return size <= FLASH_MAX_CMD_PROGRAM_SIZE;
}

/**
  * @brief Check flash program address.
  * @param addr program address, unit:Byte(8bit).
  * @retval true
  * @retval false
  */
static inline bool IsFlashProgramAddress(unsigned int addr)
{
    return (((addr % FLASH_MIN_PGM_BYTES_SIZE) == 0) && (addr < FLASH_MAX_SIZE));
}

/**
  * @brief Check flash erase address.
  * @param addr erase address, unit:Byte(8bit).
  * @retval true
  * @retval false
  */
static inline bool IsFlashEraseAddress(unsigned int addr)
{
    return ((addr % FLASH_ONE_PAGE_SIZE) == 0) && (addr <= FLASH_PAGE_MAX);
}

/**
  * @brief Check flash write source addresss.
  * @param addr write source addresss.
  * @retval true
  * @retval false
  */
static inline bool IsFlashWriteSrcAddress(unsigned int addr)
{
    return ((addr >= FLASH_SRAM_START_ADDRESS && addr <= FLASH_SRAM_END_ADDRESS) ||
            (addr >= FLASH_MAIN_RNG_START_ADDRESS && addr <= FLASH_MAIN_RNG_END_ADDRESS));
}

/**
  * @brief Check flash erase mode.
  * @param mode flash erase mode.
  * @retval true
  * @retval false
  */
static inline bool IsFlashEraseMode(FLASH_EraseMode mode)
{
    return (mode == FLASH_ERASE_MODE_PAGE || mode == FLASH_ERASE_MODE_CHIP);
}

/**
  * @brief Enable flash command start.
  * @param efc FLASH register base address.
  * @retval None.
  */
static inline void DCL_FLASH_CmdStartEnable(EFC_RegStruct *efcx)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    efcx->EFLASH_CMD.BIT.cmd_start = BASE_CFG_ENABLE;
}

/**
  * @brief Disable flash command start.
  * @param efcx FLASH register base address.
  * @retval None.
  */
static inline void DCL_FLASH_CmdStartDisable(EFC_RegStruct *efcx)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    efcx->EFLASH_CMD.BIT.cmd_start = BASE_CFG_DISABLE;
}

/**
  * @brief Getting flash command start State.
  * @param efcx FLASH register base address.
  * @retval command start value, 1: Operation complete or no operation, 0: Operation is not complete.
  */
static inline unsigned int DCL_FLASH_GetCmdStartState(const EFC_RegStruct *efcx)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    return efcx->EFLASH_CMD.BIT.cmd_start;
}

/**
  * @brief Setting FLASH cmd code.
  * @param efcx FLASH register base address.
  * @param cmdCode flash cmd code.
  * @retval None.
  */
static inline void DCL_FLASH_SetCmdCode(EFC_RegStruct *efcx, FLASH_CmdCodeType cmdCode)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    FLASH_PARAM_CHECK_NO_RET(IsFlashCmdCode(cmdCode));
    efcx->EFLASH_CMD.BIT.cmd_code = cmdCode;
}

/**
  * @brief Getting FLASH cmd code.
  * @param efcx FLASH register base address.
  * @param cmdCode flash cmd code.
  * @retval cmd code, 1:READ, 2:FLASH_CMD_MAIN_PROGEAM, 3:FLASH_CMD_INFO_PROGEAM, 4:FLASH_CMD_MAIN_ERASE,
                      5:FLASH_CMD_INFO_ERASE, 6:FLASH_CMD_MASS_ERASE.
  */
static inline unsigned int DCL_FLASH_GetCmdCode(const EFC_RegStruct *efcx)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    return efcx->EFLASH_CMD.BIT.cmd_code;
}

/**
  * @brief Setting FLASH cmd program size.
  * @param efcx FLASH register base address.
  * @param size flash cmd program size, unit:Word(32bit).
  * @retval None.
  */
static inline void DCL_FLASH_SetCmdProgramSize(EFC_RegStruct *efcx, unsigned int size)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    FLASH_PARAM_CHECK_NO_RET(IsFlashCmdProgramSize(size));
    efcx->EFLASH_CMD.BIT.cmd_pgm_size = size;
}

/**
  * @brief Getting FLASH cmd program size.
  * @param efcx FLASH register base address.
  * @retval cmd program size, unit:Word(32bit).
  */
static inline unsigned int DCL_FLASH_GetCmdProgramSize(const EFC_RegStruct *efcx)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    return efcx->EFLASH_CMD.BIT.cmd_pgm_size;
}

/**
  * @brief Setting FLASH program start address.
  * @param efcx FLASH register base address.
  * @param addr flash cmd program start address, unit:Byte(8bit).
  * @retval None.
  */
static inline void DCL_FLASH_SetProgramAddress(EFC_RegStruct *efcx, unsigned int addr)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    FLASH_PARAM_CHECK_NO_RET(IsFlashProgramAddress(addr));
    efcx->EFLASH_ADDR.BIT.cmd_addr = addr;
}

/**
  * @brief Setting FLASH erase start address.
  * @param efcx FLASH register base address.
  * @param addr flash cmd erase start address, unit:Byte(8bit).
  * @retval None.
  */
static inline void DCL_FLASH_SetEraseAddress(EFC_RegStruct *efcx, unsigned int addr)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    FLASH_PARAM_CHECK_NO_RET(IsFlashEraseAddress(addr));
    efcx->EFLASH_ADDR.BIT.cmd_addr = addr;
}

/**
  * @brief Getting FLASH cmd program, erase, read start address.
  * @param efcx FLASH register base address.
  * @retval cmd program, erase, read start address, unit:Byte(8bit).
  */
static inline unsigned int DCL_FLASH_GetCmdStartAddress(const EFC_RegStruct *efcx)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    return efcx->EFLASH_ADDR.BIT.cmd_addr;
}

/**
  * @brief Setting FLASH operation mode.
  * @param efcx FLASH register base address.
  * @param mode flash operation mode.
  * @retval None.
  */
static inline void DCL_FLASH_SetOptMode(EFC_RegStruct *efcx, FLASH_PE_OpMode mode)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    FLASH_PARAM_CHECK_NO_RET(IsFlashOperationMode(mode));
    efcx->CMD_CFG_COMMON.BIT.int_mode = mode;
}

/**
  * @brief Getting FLASH operation mode.
  * @param efcx FLASH register base address.
  * @retval operation mode, 0:FLASH_PE_OP_BLOCK, 1:FLASH_PE_OP_IT.
  */
static inline unsigned int DCL_FLASH_GetOptMode(const EFC_RegStruct *efcx)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    return efcx->CMD_CFG_COMMON.BIT.int_mode;
}

/**
  * @brief Obtains the interrupt status.
  * @param efcx FLASH register base address.
  * @retval Interrupt Status.
  */
static inline unsigned int DCL_FLASH_GetInterrupRawtStatus(const EFC_RegStruct *efcx)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    return efcx->INT_RAW_STATUS.reg;
}

/**
  * @brief Configuring Interrupt Enable.
  * @param efcx FLASH register base address.
  * @param intrEn Corresponding interrupt enable bit, for example, 110011.
  * @retval None.
  */
static inline void DCL_FLASH_SetInterruptEn(EFC_RegStruct *efcx, unsigned int intrEn)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    efcx->INT_ENABLE.reg = intrEn;
}

/**
  * @brief Obtaining the Interrupt Enable Configuration.
  * @param efcx FLASH register base address.
  * @retval Interrupt enable value.
  */
static inline unsigned int DCL_FLASH_GetInterruptEnState(const EFC_RegStruct *efcx)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    return efcx->INT_ENABLE.reg;
}

/**
  * @brief Clear Interrupt.
  * @param efcx FLASH register base address.
  * @param intrRaw Corresponding interrupt bit, for example, 110011.
  * @retval None.
  */
static inline void DCL_FLASH_ClearIrq(EFC_RegStruct *efcx, unsigned int intrRaw)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    efcx->INT_CLEAR.reg = intrRaw;
}

/**
  * @brief FLASH cache invalid request enable.
  * @param efcx FLASH register base address.
  * @retval None.
  */
static inline void DCL_FLASH_CacheInvalidRequestEnable(EFC_RegStruct *efcx)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    efcx->CACHE_CTRL.BIT.cache_invalid_req = BASE_CFG_ENABLE;
}

/**
  * @brief FLASH cache invalid request disable.
  * @param efcx FLASH register base address.
  * @retval None.
  */
static inline void DCL_FLASH_CacheInvalidRequestDisable(EFC_RegStruct *efcx)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    efcx->CACHE_CTRL.BIT.cache_invalid_req = BASE_CFG_DISABLE;
}

/**
  * @brief Getting FLASH cache invalid request state.
  * @param efcx FLASH register base address.
  * @retval state 0:The latest invalid request has been completed,
                  1:The latest invalid request is not completed.
  */
static inline unsigned int DCL_FLASH_GetCacheInvalidRequestState(const EFC_RegStruct *efcx)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    return efcx->CACHE_CTRL.BIT.cache_invalid_req;
}

/**
  * @brief Getting FLASH command operation status.
  * @param efcx FLASH register base address.
  * @retval command operation status.
  */
static inline unsigned int DCL_FLASH_GetCommandOptStatus(const EFC_RegStruct *efcx)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    return efcx->FLASH_STATUS.reg;
}

/**
  * @brief Setting FLASH magic lock.
  * @param efcx FLASH register base address.
  * @retval None.
  */
static inline void DCL_FLASH_MagicLock(EFC_RegStruct *efcx)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    efcx->MAGIC_LOCK = FLASH_KEY_REGISTER_LOCK_VALUE;
}

/**
  * @brief Setting FLASH magic unlock.
  * @param efcx FLASH register base address.
  * @retval None.
  */
static inline void DCL_FLASH_MagicUnlock(EFC_RegStruct *efcx)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    efcx->MAGIC_LOCK = FLASH_KEY_REGISTER_UNLOCK_VALUE;
}

/**
  * @brief Getting FLASH magic lock.
  * @param efcx FLASH register base address.
  * @retval The value of magic lock, The value 0xFEDC_BA98 indicates magic unlock, others values is magic lock.
  */
static inline unsigned int DCL_FLASH_GetMagicLock(const EFC_RegStruct *efcx)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    return efcx->MAGIC_LOCK;
}

/**
  * @brief Setting FLASH program wdata value.
  * @param efcx FLASH register base address.
  * @param value The value of program wdata.
  * @retval None.
  */
static inline void DCL_FLASH_SetProgramWdata(EFC_RegStruct *efcx, unsigned int value)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    efcx->PGM_WDATA = value;
}

/**
  * @brief FLASH program wdata celar enable.
  * @param efcx FLASH register base address.
  * @retval None.
  */
static inline void DCL_FLASH_ProgramWdataClearEnable(EFC_RegStruct *efcx)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    efcx->BUF_CLEAR.BIT.pgm_wdata_clr = BASE_CFG_ENABLE;
}

/**
  * @brief FLASH program wdata celar disable.
  * @param efcx FLASH register base address.
  * @retval None.
  */
static inline void DCL_FLASH_ProgramWdataClearDisable(EFC_RegStruct *efcx)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    efcx->BUF_CLEAR.BIT.pgm_wdata_clr = BASE_CFG_DISABLE;
}

/**
  * @brief Getting FLASH buf clear value.
  * @param efcx FLASH register base address.
  * @retval None.
  */
static inline unsigned int DCL_FLASH_GetBufClearValue(const EFC_RegStruct *efcx)
{
    FLASH_ASSERT_PARAM(IsEFCInstance(efcx));
    return efcx->BUF_CLEAR.reg;
}

/**
  * @}
  */

/**
  * @}
  */
#endif /* #ifndef McuMagicTag_FLASH_IP_H */